title: Hannah Wagner # your name (or website title) here
logo: "/images/HWagner_Headshot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of City Planning Candidate at the University of Pennsylvania Weitzman School of Design<br><br>
  Climate Adaptation & Resilience<br><br>
  (she/her)<br><br>
   
  <a href="https://www.linkedin.com/in/hannah-wagner-077288a7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
